In [2]:
import numpy as np

just cehcking

The basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


# Get dimension of array 


In [6]:
b.ndim

2

In [ ]:
# Get the shape of the array
b.shape
#(row,columns) = (2,3)

(2, 3)

In [ ]:
#get type of the array
b.dtype

dtype('int64')