In [2]:
import numpy as np

just cehcking

# The basics

In [11]:
a = np.array([1,2,3], dtype=np.int32)
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
b.ndim

2

In [ ]:
# Get the shape of the array
b.shape
#(row,columns) = (2,3)

(2, 3)

In [10]:
#get type of the array
b.dtype

dtype('float64')

In [12]:
a.dtype

dtype('int32')

In [14]:
a.itemsize
#provide the byte size of each element in the array

4

In [16]:
a.size*a.itemsize
# get total size of the array

12

# Accessing/Changing specific elements,rows,columns,etc

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
# Get the specific element 
a[1,-2]

np.int64(13)

In [20]:
#get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#get a specific column
a[:,2]

array([ 3, 10])

In [ ]:
#getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [24]:
#changing elements
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [25]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [26]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [27]:
#3-d example 
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
#get specific element (work outside in)
print(b[0,1,1])
b[:,0,:]

4


array([[1, 2],
       [5, 6]])

In [31]:
#replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Type Of Arrays

In [ ]:
#all 0s matrix
np.zeros((5))
np.zeros((2,3))
#and so on 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
#all 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [38]:
#Any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [40]:
#any otehr number(full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [42]:
#random decimal numbers
np.random.rand(4,2,3)

array([[[0.72853947, 0.27775559, 0.00866056],
        [0.39167777, 0.44704183, 0.84962882]],

       [[0.89886215, 0.23557416, 0.94836404],
        [0.57397387, 0.28067112, 0.27061104]],

       [[0.89322558, 0.11173241, 0.29131182],
        [0.2181597 , 0.39693769, 0.10251018]],

       [[0.35017394, 0.65667563, 0.87874104],
        [0.31791071, 0.4731147 , 0.75890292]]])

In [ ]:
#random integers value
np.random.randint(7, size=(3,3))
# 7 -stop value  ie from 0 - 7

array([[6, 3, 4],
       [3, 2, 1],
       [2, 3, 4]], dtype=int32)

In [45]:
np.random.randint(4,8, size=(3,3))

array([[7, 6, 7],
       [7, 4, 5],
       [4, 5, 4]], dtype=int32)

In [46]:
#identity matrix 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
#repeatinf a array few timem

arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3 , axis=0)#axis = 0 makes it 2-d array 
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [58]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.array([1,2,3])
b = a#b points to the same array as a, so changing b will also change a
b[0] = 100 
print(a)
print(b)

[100   2   3]
[100   2   3]


In [62]:
a = np.array([1,2,3])
b = a.copy()#b is now a copy of a, so changing b will NOT change a
b[0] = 100
print(a)    
print(b)

[1 2 3]
[100   2   3]


# Mathematics

In [63]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = a+b
print(c)

[ 6  8 10 12]


In [64]:
a = np.array([1,2,3])
a+2

array([3, 4, 5])

In [65]:
a - 2

array([-1,  0,  1])

In [66]:
a*2

array([2, 4, 6])

In [69]:
b = np.array([1,0,1])
a + b

array([2, 2, 4])

In [70]:
a ** 2

array([1, 4, 9])

In [72]:
#take the sin,cos,tan
np.sin(a)
np.cos(a)
np.tan(a)


array([ 1.55740772, -2.18503986, -0.14254654])

## Linear Algebra

In [74]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
#find the determinant of a matrix
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [ ]:
#Reference docs(https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

#determinant 
#trace
#singualr vector decomposition 
#eigen values
#matrix norm 
#inverse 
#etc..


## Statitics

In [77]:
stats = np.array([[1,2,3],[4,5,6]])


In [ ]:
np.min(stats, )

np.int64(1)

In [80]:
np.max(stats)

np.int64(6)

In [ ]:
np.sum(stats, axis = 0) #axis = 0 means column while axis = 1 means row wise sum

array([5, 7, 9])

# Reorganizing Arrays

In [83]:
before = np.array([[1,2,3],[4,5,6]])
print(before.shape)
after = before.reshape((3,2))
print(after)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [84]:
# vertically stacking matrices

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
# horizontally stacking matrices
h1 = np.ones((2,4))
h2 = np.zeros((2,2))


np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# miscellaneous

In [87]:
# we can get load data from file 
filedata = np.genfromtxt('data.txt', delimiter=',')#data.txt file is in the same directory as this notebook
# delimiter is used to specify the character that separates the values in the file. In this case, it is a comma (',').



filedata = filedata.astype('int32')#convert the data to int32 type



FileNotFoundError: data.txt not found.

### Boolean masking adn Advanced indexing

In [ ]:
filedata[filedata > 50]#get all the values greater than 50


In [88]:
## you can index with a list in numpy

a = np.array([1,2,3,4,5,6,7,8,9,10])
a[[1,2,3]]

array([2, 3, 4])